In [13]:
cd /mnt/c/Users/wjdgu/OneDrive/바탕 화면/Euron-5th-Mid-DL

/mnt/c/Users/wjdgu/OneDrive/바탕 화면/Euron-5th-Mid-DL


In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os

print(os.listdir("/mnt/c/Users/wjdgu/OneDrive/바탕 화면/Euron-5th-Mid-DL/input"))

['sample_submission.csv', 'test.csv', 'train.csv']


## Basics of Pytorch
Matrices
- In pytorch, matrix(array) is called tensors.
- 3*3 matrix koy. This is 3x3 tensor

In [20]:
# numpy array
array = [[1,2,3],[4,5,6]]
first_array = np.array(array)

print(type(first_array)) # type
print(np.shape(first_array)) # shape
print(first_array)

<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [4 5 6]]


- Now examine how we implement tensor
- we create tensor with torch.Tensor() method

In [21]:
import torch

# pytorch array
tensor = torch.Tensor(array) # array는 바로 위 block에서 정의된 배열, array -> torch
print(tensor.type)
print(tensor.shape)
print(tensor)

<built-in method type of Tensor object at 0x7f961befc1d0>
torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


Allocation is one of the most used technique in coding. Therefore lets learn how to make it with pytorch

In [22]:
print(np.ones((2,3))) # numpy

print(torch.ones((2,3))) # torch

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [24]:
print(np.random.rand(2,3)) # numpy

print(torch.rand(2,3)) # torch

[[0.49237428 0.70286046 0.05983835]
 [0.07735758 0.42875591 0.37256638]]
tensor([[0.9183, 0.9480, 0.2935],
        [0.5181, 0.2476, 0.9183]])


Usually convert result of neural network that is tensor to numpy array to visualize or examine

In [26]:
# random numpy array
array = np.random.rand(2,2)
print(type(array))

# from numpy to tensor
fnumpy_ttensor = torch.from_numpy(array)
print(fnumpy_ttensor)

# from tensro to numpy
tensor = fnumpy_ttensor
ftensor_tnumpy = tensor.numpy()
print(ftensor_tnumpy)
print(type(ftensor_tnumpy))


<class 'numpy.ndarray'>
tensor([[0.4623, 0.3579],
        [0.3618, 0.3410]], dtype=torch.float64)
[[0.46233129 0.35790105]
 [0.36181816 0.34097045]]
<class 'numpy.ndarray'>


### Basic Math with Pytorch
- Resize: view()
- a and b are tensor.
- Addition: torch.add(a,b) = a + b
- Subtraction: a.sub(b) = a - b
- Element wise multiplication: torch.mul(a,b) = a * b
- Element wise division: torch.div(a,b) = a / b
- Mean: a.mean()
- Standart Deviation (std): a.std()

In [28]:
tensor = torch.ones(3,3)

print(tensor)

print(tensor.view(9).shape, tensor.view(9))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([9]) tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [29]:
print(torch.add(tensor,tensor))

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [32]:
print(tensor.sub(tensor)) # tensor에서 tensor 빼기

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [33]:
print(tensor) # tensor값 자체가 변하진 않음

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [31]:
print(torch.mul(tensor,tensor))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [34]:
print(torch.div(tensor,tensor))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [36]:
tensor=torch.Tensor([1,2,3,4,5])
print(tensor.mean())
print(tensor.std())

tensor(3.)
tensor(1.5811)


## Variables
We will use pytorch in neural network. Therefore we need to handle gradients.
- Deep learning tutorial : https://www.kaggle.com/kanncaa1/deep-learning-tutorial-for-beginners
- Difference between variables and tensor is variable accumulates gradients.
- We can make math operations with variables, too.
- In order to make backward propagation we need variables

In [37]:
from torch.autograd import Variable
var = Variable(torch.ones(3), requires_grad=True)
var
################################### In[8]

tensor([1., 1., 1.], requires_grad=True)